In [21]:
%load_ext autoreload
%autoreload 2

In [ ]:
import sys
print(sys.executable)

c:\Users\paula\Documents\Cours\A4\S2\WebData\Project\f1_semantic_web_project\.venv\Scripts\python.exe

UsageError: Line magic function `%autoreload` not found.

In [5]:
from pathlib import Path
import sys

project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

from src.crawl.io_utils import load_seed_urls

urls = load_seed_urls("../data/raw/seed_urls.txt")
urls

['https://www.formula1.com/en/drivers',
 'https://www.formula1.com/en/teams',
 'https://www.formula1.com/en/racing/2025',
 'https://www.formula1.com/en/results/2024/races',
 'https://www.formula1.com/en/results/2024/drivers',
 'https://www.formula1.com/en/results/2024/team',
 'https://www.formulaonehistory.com/seasons/',
 'https://www.formulaonehistory.com/circuits/',
 'https://www.formulaonehistory.com/results/',
 'https://www.formulaonehistory.com/category/history/grand-prix-winners/']

In [6]:
from src.crawl.web_utils import fetch_page

url = urls[0]
html = fetch_page(url)

print(type(html))
print(len(html))
print(html[:500])

<class 'str'>
622833
<!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="preload" as="image" href="https://media.formula1.com/image/upload/c_lfill,w_720/q_auto/v1740000001/fom-website/static-assets/2026/races/card/china.webp"/><link rel="preload" as="image" href="https://media.formula1.com/image/upload/c_lfill,w_1296/q_auto/v1740000001/fom-website/static-assets/2026/races/card/japan.webp"/><link rel="preload" as="image" href="htt

In [7]:
from src.crawl.io_utils import save_text

output_path = "../data/raw/test_page.html"
save_text(html, output_path)

print(f"Saved file to: {output_path}")

Saved file to: ../data/raw/test_page.html

In [8]:
from pathlib import Path

Path("../data/raw/test_page.html").exists()

True

In [9]:
from src.crawl.io_utils import load_seed_urls, save_text
from src.crawl.web_utils import fetch_page

urls = load_seed_urls("../data/raw/seed_urls.txt")

first_url = urls[0]
html = fetch_page(first_url)

output_path = "../data/raw/first_seed_page.html"
save_text(html, output_path)

print("URL fetched:", first_url)
print("Saved to:", output_path)
print("HTML length:", len(html))

URL fetched: https://www.formula1.com/en/drivers
Saved to: ../data/raw/first_seed_page.html
HTML length: 622833

In [10]:
from pathlib import Path

from src.crawl.io_utils import load_seed_urls, save_text
from src.crawl.web_utils import fetch_page

urls = load_seed_urls("../data/raw/seed_urls.txt")

for i, url in enumerate(urls, start=1):
    html = fetch_page(url)
    output_path = f"../data/raw/seed_page_{i}.html"
    save_text(html, output_path)
    print(f"[{i}] Saved {url} -> {output_path} ({len(html)} chars)")

[1] Saved https://www.formula1.com/en/drivers -> ../data/raw/seed_page_1.html (622833 chars)
[2] Saved https://www.formula1.com/en/teams -> ../data/raw/seed_page_2.html (472299 chars)
[3] Saved https://www.formula1.com/en/racing/2025 -> ../data/raw/seed_page_3.html (774477 chars)
[4] Saved https://www.formula1.com/en/results/2024/races -> ../data/raw/seed_page_4.html (611020 chars)
[5] Saved https://www.formula1.com/en/results/2024/drivers -> ../data/raw/seed_page_5.html (482889 chars)
[6] Saved https://www.formula1.com/en/results/2024/team -> ../data/raw/seed_page_6.html (433877 chars)
[7] Saved https://www.formulaonehistory.com/seasons/ -> ../data/raw/seed_page_7.html (215646 chars)
[8] Saved https://www.formulaonehistory.com/circuits/ -> ../data/raw/seed_page_8.html (263058 chars)
[9] Saved https://www.formulaonehistory.com/results/ -> ../data/raw/seed_page_9.html (254850 chars)
[10] Saved https://www.formulaonehistory.com/category/history/grand-prix-winners/ -> ../data/raw/seed_page_10.html (287391 chars)

In [11]:
from pathlib import Path

sample_path = Path("../data/raw/seed_page_1.html")

with sample_path.open("r", encoding="utf-8") as file:
    html_content = file.read()

print(html_content[:2000])

<!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="preload" as="image" href="https://media.formula1.com/image/upload/c_lfill,w_720/q_auto/v1740000001/fom-website/static-assets/2026/races/card/china.webp"/><link rel="preload" as="image" href="https://media.formula1.com/image/upload/c_lfill,w_1296/q_auto/v1740000001/fom-website/static-assets/2026/races/card/japan.webp"/><link rel="preload" as="image" href="https://media.formula1.com/image/upload/c_lfill,w_720/q_auto/v1740000001/fom-website/static-assets/2026/races/card/miami.webp"/><link rel="preload" as="image" href="https://media.formula1.com/image/upload/c_lfill,w_720/q_auto/v1740000001/fom-website/static-assets/2026/races/card/canada.webp"/><link rel="preload" as="image" href="https://media.formula1.com/image/upload/t_16by9North/c_fill,w_352/q_auto/v1740000001/trackside-images/2026/F1_Grand_Prix_Of_China/2266631861.webp"/><link rel="preload" as="image" href="https://media.formula1.com/image/upload/c_fill,w_352/q_auto/v1740000001/fom-website/2026/Power%20Rankings%202026/Power%20Rankings%20Hero%20Image%202026%20DISPLAY.webp"/><link rel="preload" as="image" href="https://media.formula1.com/image/upload/c_fill,w_352/q_auto/v1740000001/fom-website/2026/Miscellaneous/btg-villeneuve-display.webp"/><link rel="preload" as="image" href="https://media.formula1.com/image/upload/t_16by9Centre/c_fill,w_352/q_auto/v1740000001/trackside-images/2026/F1_Grand_Prix_Of_China___Sprint__Qualifying/2266405064.webp"/><link rel="preload" as="image" imageSrcSet="https://d2n9h2wits23hf.cloudfront.net/image/v1/static/6057949432001/e24f8239-8614-4b38-97f9-8d0cdf0b7ef9/d2e77f62-de94-41f6-9360-3b2046d822dc/206x116/match/image.jpg 206w, https://d2n9h2wits23hf.cloudfront.net/image/v1/static/6057949432001/e24f8239-8614-4b38-97f9-8d0cdf0b7ef9/d2e77f62-de94-41f6-9360-3b2046d822dc/319x179/match/image.jpg 319w, https://d2n9h2wits23hf.cloudfront.net/image/v1/static

In [12]:
from src.crawl.text_utils import extract_main_text

clean_text = extract_main_text(html)

print(type(clean_text))
print(clean_text[:2000] if clean_text else "No text extracted")

<class 'str'>
From Adelaide to Silverstone to Monza and Spa, we chart the full story of each event’s winners from the first race to the last.
Find out about the 70th Anniversary Grand Prix winner in 2020, exploring a one-off race created to celebrate seventy years since the first World Championship in 1950.
Find a complete list of every Abu Dhabi Grand Prix winner from 2009 to today, exploring F1 drivers who won in the desert and under the lights.
Find a complete list of every Argentine Grand Prix winner from 1953 to 1998, exploring F1 drivers who won across three distinct eras of Formula One.
Find a complete list of every Australian Grand Prix winner from 1985 to today, exploring F1 drivers who won down-under in Adelaide and Melbourne.
Find a complete list of every Austrian Grand Prix winner from 1964 to today, exploring F1 drivers who won at Zeltweg, Osterreichring and Spielberg.
Find a complete list of every Azerbaijan Grand Prix winner from 2017 to today, exploring F1 drivers who survived late race twists.
Find a complete list of every Bahrain Grand Prix winner from 2004 to today, who, since 2014, have won dramatic night races under floodlights.
Find a complete list of every Barcelona-Catalunya Grand Prix winner from 2026 to today, at the legendary Circuit de Barcelona-Catalunya, which debuted in 1991.
Find a complete list of every Belgian Grand Prix winner from 1950 to today, at one of the fastest and most daunting tracks in the world.
Find a complete list of every Brazilian Grand Prix winner from 1973 to 2019, an event that's produced emotional home victories and title deciders.
Discover the drivers who won, the teams that defined eras, and moments that shaped championship battles.
From Adelaide to Silverstone to Monza and Spa, we chart the full story of each event’s winners from the first race to the last.
Lewis Hamilton leads Formula One’s all-time winners list with 105 victories, ahead of Michael Schumacher on 92 and Max Verstappen. Sebastian Vettel and Alain Prost compl

In [13]:
from src.crawl.io_utils import save_text

output_path = "../data/processed/seed_page_1.txt"
save_text(clean_text, output_path)

print(f"Saved cleaned text to: {output_path}")

with open("../data/processed/seed_page_1.txt", "r", encoding="utf-8") as file:
    preview = file.read()

print(preview[:2000])

Saved cleaned text to: ../data/processed/seed_page_1.txt
From Adelaide to Silverstone to Monza and Spa, we chart the full story of each event’s winners from the first race to the last.
Find out about the 70th Anniversary Grand Prix winner in 2020, exploring a one-off race created to celebrate seventy years since the first World Championship in 1950.
Find a complete list of every Abu Dhabi Grand Prix winner from 2009 to today, exploring F1 drivers who won in the desert and under the lights.
Find a complete list of every Argentine Grand Prix winner from 1953 to 1998, exploring F1 drivers who won across three distinct eras of Formula One.
Find a complete list of every Australian Grand Prix winner from 1985 to today, exploring F1 drivers who won down-under in Adelaide and Melbourne.
Find a complete list of every Austrian Grand Prix winner from 1964 to today, exploring F1 drivers who won at Zeltweg, Osterreichring and Spielberg.
Find a complete list of every Azerbaijan Grand Prix winner from 2017 to today, exploring F1 drivers who survived late race twists.
Find a complete list of every Bahrain Grand Prix winner from 2004 to today, who, since 2014, have won dramatic night races under floodlights.
Find a complete list of every Barcelona-Catalunya Grand Prix winner from 2026 to today, at the legendary Circuit de Barcelona-Catalunya, which debuted in 1991.
Find a complete list of every Belgian Grand Prix winner from 1950 to today, at one of the fastest and most daunting tracks in the world.
Find a complete list of every Brazilian Grand Prix winner from 1973 to 2019, an event that's produced emotional home victories and title deciders.
Discover the drivers who won, the teams that defined eras, and moments that shaped championship battles.
From Adelaide to Silverstone to Monza and Spa, we chart the full story of each event’s winners from the first race to the last.
Lewis Hamilton leads Formula One’s all-time winners list with 105 victories, ahead of Michael Schumacher on 92 and Max Verstappen. Sebastian Vettel and Alain Prost compl

In [14]:
from src.crawl.io_utils import load_seed_urls, save_text
from src.crawl.web_utils import fetch_page
from src.crawl.text_utils import extract_main_text

urls = load_seed_urls("../data/raw/seed_urls.txt")

for i, url in enumerate(urls, start=1):
    html = fetch_page(url)
    clean_text = extract_main_text(html)

    if clean_text:
        output_path = f"../data/processed/seed_page_{i}.txt"
        save_text(clean_text, output_path)
        print(f"[OK] {url} -> {output_path}")
    else:
        print(f"[SKIPPED] No text extracted for: {url}")

[OK] https://www.formula1.com/en/drivers -> ../data/processed/seed_page_1.txt
[OK] https://www.formula1.com/en/teams -> ../data/processed/seed_page_2.txt
[OK] https://www.formula1.com/en/racing/2025 -> ../data/processed/seed_page_3.txt
[OK] https://www.formula1.com/en/results/2024/races -> ../data/processed/seed_page_4.txt
[OK] https://www.formula1.com/en/results/2024/drivers -> ../data/processed/seed_page_5.txt
[OK] https://www.formula1.com/en/results/2024/team -> ../data/processed/seed_page_6.txt
[OK] https://www.formulaonehistory.com/seasons/ -> ../data/processed/seed_page_7.txt
[OK] https://www.formulaonehistory.com/circuits/ -> ../data/processed/seed_page_8.txt
[OK] https://www.formulaonehistory.com/results/ -> ../data/processed/seed_page_9.txt
[OK] https://www.formulaonehistory.com/category/history/grand-prix-winners/ -> ../data/processed/seed_page_10.txt

In [15]:
import pandas as pd

records = []
urls = load_seed_urls("../data/raw/seed_urls.txt")

for i, url in enumerate(urls, start=1):
    raw_path = f"../data/raw/seed_page_{i}.html"
    processed_path = f"../data/processed/seed_page_{i}.txt"

    html = fetch_page(url)
    save_text(html, raw_path)

    clean_text = extract_main_text(html)

    if clean_text:
        save_text(clean_text, processed_path)
        extraction_status = "ok"
    else:
        processed_path = None
        extraction_status = "failed"

    records.append({
        "page_id": i,
        "url": url,
        "raw_html_path": raw_path,
        "processed_text_path": processed_path,
        "extraction_status": extraction_status
    })

crawl_df = pd.DataFrame(records)
crawl_df

,page_id,url,raw_html_path,processed_text_path,extraction_status
0,1,https://www.formula1.com/en/drivers,../data/raw/seed_page_1.html,../data/processed/seed_page_1.txt,ok
1,2,https://www.formula1.com/en/teams,../data/raw/seed_page_2.html,../data/processed/seed_page_2.txt,ok
2,3,https://www.formula1.com/en/racing/2025,../data/raw/seed_page_3.html,../data/processed/seed_page_3.txt,ok
3,4,https://www.formula1.com/en/results/2024/races,../data/raw/seed_page_4.html,../data/processed/seed_page_4.txt,ok
4,5,https://www.formula1.com/en/results/2024/drivers,../data/raw/seed_page_5.html,../data/processed/seed_page_5.txt,ok
5,6,https://www.formula1.com/en/results/2024/team,../data/raw/seed_page_6.html,../data/processed/seed_page_6.txt,ok
6,7,https://www.formulaonehistory.com/seasons/,../data/raw/seed_page_7.html,../data/processed/seed_page_7.txt,ok
7,8,https://www.formulaonehistory.com/circuits/,../data/raw/seed_page_8.html,../data/processed/seed_page_8.txt,ok
8,9,https://www.formulaonehistory.com/results/,../data/raw/seed_page_9.html,../data/processed/seed_page_9.txt,ok
9,10,https://www.formulaonehistory.com/category/his...,../data/raw/seed_page_10.html,../data/processed/seed_page_10.txt,ok

In [16]:
crawl_df.to_csv("../data/processed/crawl_manifest.csv", index=False)
print("Manifest saved to ../data/processed/crawl_manifest.csv")

Manifest saved to ../data/processed/crawl_manifest.csv

In [17]:
from src.crawl.pipeline import crawl_seed_urls
import pandas as pd

records = crawl_seed_urls("data/raw/seed_urls.txt")
crawl_df = pd.DataFrame(records)

crawl_df

,page_id,url,raw_html_path,processed_text_path,extraction_status
0,1,https://www.formula1.com/en/drivers,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
1,2,https://www.formula1.com/en/teams,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
2,3,https://www.formula1.com/en/racing/2025,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
3,4,https://www.formula1.com/en/results/2024/races,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
4,5,https://www.formula1.com/en/results/2024/drivers,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
5,6,https://www.formula1.com/en/results/2024/team,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
6,7,https://www.formulaonehistory.com/seasons/,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
7,8,https://www.formulaonehistory.com/circuits/,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
8,9,https://www.formulaonehistory.com/results/,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
9,10,https://www.formulaonehistory.com/category/his...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok

In [19]:
from src.crawl.io_utils import save_records_to_csv

save_records_to_csv(records, "../data/processed/crawl_manifest.csv")
print("Manifest saved.")

Manifest saved.

In [20]:
import pandas as pd

manifest_df = pd.read_csv("../data/processed/crawl_manifest.csv")
manifest_df

,page_id,url,raw_html_path,processed_text_path,extraction_status
0,1,https://www.formula1.com/en/drivers,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
1,2,https://www.formula1.com/en/teams,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
2,3,https://www.formula1.com/en/racing/2025,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
3,4,https://www.formula1.com/en/results/2024/races,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
4,5,https://www.formula1.com/en/results/2024/drivers,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
5,6,https://www.formula1.com/en/results/2024/team,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
6,7,https://www.formulaonehistory.com/seasons/,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
7,8,https://www.formulaonehistory.com/circuits/,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
8,9,https://www.formulaonehistory.com/results/,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
9,10,https://www.formulaonehistory.com/category/his...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok

In [22]:
from src.crawl.pipeline import crawl_seed_urls_and_save_manifest
import pandas as pd

records = crawl_seed_urls_and_save_manifest(
    "data/raw/seed_urls.txt",
    "../data/processed/crawl_manifest.csv",
)

crawl_df = pd.DataFrame(records)
crawl_df.head()

,page_id,url,raw_html_path,processed_text_path,extraction_status
0,1,https://www.formula1.com/en/drivers,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
1,2,https://www.formula1.com/en/teams,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
2,3,https://www.formula1.com/en/racing/2025,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
3,4,https://www.formula1.com/en/results/2024/races,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok
4,5,https://www.formula1.com/en/results/2024/drivers,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,C:\Users\paula\Documents\Cours\A4\S2\WebData\P...,ok