In [1]:
%load_ext autoreload
%autoreload 2

from pathlib import Path
import sys

project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

print("Project root:", project_root)
print("Python executable:", sys.executable)

Project root: c:\Users\paula\Documents\Cours\A4\S2\WebData\Project\f1_semantic_web_project
Python executable: c:\Users\paula\Documents\Cours\A4\S2\WebData\Project\f1_semantic_web_project\.venv\Scripts\python.exe

In [2]:
import sys
print(sys.executable)

c:\Users\paula\Documents\Cours\A4\S2\WebData\Project\f1_semantic_web_project\.venv\Scripts\python.exe

In [3]:
import sys
import spacy

print(sys.executable)

nlp = spacy.load("en_core_web_sm")
print("spaCy loaded successfully")
print(nlp.pipe_names)

c:\Users\paula\Documents\Cours\A4\S2\WebData\Project\f1_semantic_web_project\.venv\Scripts\python.exe
spaCy loaded successfully
['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [4]:
from pathlib import Path

sample_path = Path("../data/processed/seed_page_1.txt")

with sample_path.open("r", encoding="utf-8") as file:
    text = file.read()

print(text[:1500])

Authentics
Store
Tickets
Hospitality
Experiences
Previous
Next
Upcoming
Inside the 2026 F1 titles shoot
Team Bosses Unfiltered: Team Culture
Find the current Formula 1 drivers for the 2026 season
George
Russell
Mercedes
Kimi
Antonelli
Charles
Leclerc
Ferrari
Lewis
Hamilton
Lando
Norris
McLaren
Oscar
Piastri
Esteban
Ocon
Haas F1 Team
Oliver
Bearman
Max
Verstappen
Red Bull Racing
Isack
Hadjar
Liam
Lawson
Racing Bulls
Arvid
Lindblad
Pierre
Gasly
Alpine
Franco
Colapinto
Nico
Hulkenberg
Audi
Gabriel
Bortoleto
Carlos
Sainz
Williams
Alexander
Albon
Sergio
Perez
Cadillac
Valtteri
Bottas
Fernando
Alonso
Aston Martin
Lance
Stroll

In [5]:
doc = nlp(text[:3000])

entities = [(ent.text, ent.label_) for ent in doc.ents]
entities[:30]

[('2026', 'DATE'),
 ('Team Bosses Unfiltered: Team Culture\nFind', 'ORG'),
 ('Formula 1', 'LAW'),
 ('2026', 'DATE'),
 ('George\nRussell\nMercedes', 'PERSON'),
 ('Charles\nLeclerc', 'PERSON'),
 ('Ferrari\nLewis\nHamilton\nLando\nNorris\nMcLaren\nOscar\nPiastri\nEsteban',
  'ORG'),
 ('Ocon', 'ORG'),
 ('Haas F1 Team\nOliver\nBearman\nMax\nVerstappen\n', 'ORG'),
 ('Liam\nLawson\n', 'PERSON'),
 ('Williams', 'PERSON'),
 ('Alexander\nAlbon\nSergio\nPerez\nCadillac', 'PERSON'),
 ('Valtteri', 'ORG'),
 ('Alonso', 'PERSON'),
 ('Aston Martin\nLance\nStroll', 'PERSON')]

In [10]:
from src.ie.preprocessing import normalize_text

normalized_text = normalize_text(text)

print(normalized_text[:1500])

Authentics Store Tickets Hospitality Experiences Previous Next Upcoming Inside the 2026 F1 titles shoot Team Bosses Unfiltered: Team Culture Find the current Formula 1 drivers for the 2026 season George Russell Mercedes Kimi Antonelli Charles Leclerc Ferrari Lewis Hamilton Lando Norris McLaren Oscar Piastri Esteban Ocon Haas F1 Team Oliver Bearman Max Verstappen Red Bull Racing Isack Hadjar Liam Lawson Racing Bulls Arvid Lindblad Pierre Gasly Alpine Franco Colapinto Nico Hulkenberg Audi Gabriel Bortoleto Carlos Sainz Williams Alexander Albon Sergio Perez Cadillac Valtteri Bottas Fernando Alonso Aston Martin Lance Stroll

In [11]:
doc = nlp(normalized_text[:3000])
entities = [(ent.text, ent.label_) for ent in doc.ents]
entities[:30]

[('2026', 'DATE'),
 ('Team Bosses Unfiltered: Team Culture Find', 'ORG'),
 ('Formula 1', 'LAW'),
 ('2026', 'DATE'),
 ('George Russell Mercedes', 'PERSON'),
 ('Antonelli Charles Leclerc', 'PERSON'),
 ('Hamilton Lando', 'PERSON'),
 ('Norris', 'PERSON'),
 ('Oscar Piastri', 'PERSON'),
 ('Haas F1 Team', 'ORG'),
 ('Oliver Bearman Max Verstappen', 'PERSON'),
 ('Hadjar Liam Lawson', 'PERSON'),
 ('Arvid Lindblad', 'PERSON'),
 ('Pierre Gasly Alpine Franco', 'PERSON'),
 ('Nico Hulkenberg Audi', 'PERSON'),
 ('Gabriel Bortoleto Carlos Sainz Williams', 'PERSON'),
 ('Alexander Albon', 'PERSON'),
 ('Perez Cadillac', 'PERSON'),
 ('Valtteri', 'PRODUCT'),
 ('Fernando Alonso', 'PERSON'),
 ('Martin Lance Stroll', 'PERSON')]

In [12]:
from pathlib import Path

processed_dir = Path("../data/processed")
txt_files = sorted(processed_dir.glob("seed_page_*.txt"))

for path in txt_files:
    with path.open("r", encoding="utf-8") as file:
        content = file.read()

    normalized = normalize_text(content)

    print("=" * 100)
    print(path.name)
    print("Length:", len(normalized))
    print(normalized[:1200])
    print()

====================================================================================================
seed_page_1.txt
Length: 627
Authentics Store Tickets Hospitality Experiences Previous Next Upcoming Inside the 2026 F1 titles shoot Team Bosses Unfiltered: Team Culture Find the current Formula 1 drivers for the 2026 season George Russell Mercedes Kimi Antonelli Charles Leclerc Ferrari Lewis Hamilton Lando Norris McLaren Oscar Piastri Esteban Ocon Haas F1 Team Oliver Bearman Max Verstappen Red Bull Racing Isack Hadjar Liam Lawson Racing Bulls Arvid Lindblad Pierre Gasly Alpine Franco Colapinto Nico Hulkenberg Audi Gabriel Bortoleto Carlos Sainz Williams Alexander Albon Sergio Perez Cadillac Valtteri Bottas Fernando Alonso Aston Martin Lance Stroll

====================================================================================================
seed_page_10.txt
Length: 3923
From Adelaide to Silverstone to Monza and Spa, we chart the full story of each event’s winners from the first race to the last. Find out about the 70th Anniversary Grand Prix winner in 2020, exploring a one-off race created to celebrate seventy years since the first World Championship in 1950. Find a complete list of every Abu Dhabi Grand Prix winner from 2009 to today, exploring F1 drivers who won in the desert and under the lights. Find a complete list of every Argentine Grand Prix winner from 1953 to 1998, exploring F1 drivers who won across three distinct eras of Formula One. Find a complete list of every Australian Grand Prix winner from 1985 to today, exploring F1 drivers who won down-under in Adelaide and Melbourne. Find a complete list of every Austrian Grand Prix winner from 1964 to today, exploring F1 drivers who won at Zeltweg, Osterreichring and Spielberg. Find a complete list of every Azerbaijan Grand Prix winner from 2017 to today, exploring F1 drivers who survived late race twists. Find a complete list of every Bahrain Grand Prix winner from 2004 to today, who, since 2014, have won dramatic night races under floodlights. Find a complete list of every Barcelona-Catalu

====================================================================================================
seed_page_2.txt
Length: 596
F1 Teams 2026 Find the current Formula 1 teams for the 2026 season Mercedes George RussellKimi AntonelliFerrari Charles LeclercLewis HamiltonMcLaren Lando NorrisOscar PiastriHaas F1 Team Esteban OconOliver BearmanRed Bull Racing Max VerstappenIsack HadjarRacing Bulls Liam LawsonArvid LindbladAlpine Pierre GaslyFranco ColapintoAudi Nico HulkenbergGabriel BortoletoWilliams Carlos SainzAlexander AlbonCadillac Sergio PerezValtteri BottasAston Martin Fernando AlonsoLance Stroll2026 F1 DRIVERSCheck out this season's official F1 line-up by following your favourite F1 drivers on and off the track.

====================================================================================================
seed_page_3.txt
Length: 2918
2025 FIA FORMULA ONE WORLD CHAMPIONSHIP™ RACE CALENDAR Bahrain FORMULA 1 ARAMCO PRE-SEASON TESTING 202526 - 28 FebAustralia FORMULA 1 LOUIS VUITTON AUSTRALIAN GRAND PRIX 2025NorrisNOR 1:42:06.304 VerstappenVER +0.895 RussellRUS +8.481 China FORMULA 1 HEINEKEN CHINESE GRAND PRIX 2025PiastriPIA 1:30:55.026 NorrisNOR +9.748 RussellRUS +11.097 Japan FORMULA 1 LENOVO JAPANESE GRAND PRIX 2025VerstappenVER 1:22:06.983 NorrisNOR +1.423 PiastriPIA +2.129 Bahrain FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2025PiastriPIA 1:35:39.435 RussellRUS +15.499 NorrisNOR +16.273 Saudi Arabia FORMULA 1 STC SAUDI ARABIAN GRAND PRIX 2025PiastriPIA 1:21:06.758 VerstappenVER +2.843 LeclercLEC +8.104 Miami FORMULA 1 CRYPTO.COM MIAMI GRAND PRIX 2025PiastriPIA 1:28:51.587 NorrisNOR +4.63 RussellRUS +37.644 Emilia-Romagna FORMULA 1 AWS GRAN PREMIO DEL MADE IN ITALY E DELL'EMILIA-ROMAGNA 2025VerstappenVER 1:31:33.199 NorrisNOR +6.109 PiastriPIA +12.956 Monaco FORMULA 1 TAG HEUER GRAND PRIX DE MONACO 2025NorrisNOR 1:40:33.843 LeclercLEC +3.131 PiastriPIA +3.658 Spain FORMULA 1 ARAMCO GRAN PREMIO DE ESPAÑA 2025PiastriPIA 1:32:57.375 NorrisNOR +2.471 LeclercLEC +10.455 Canada FORMULA 1 PIRELLI GRAND PRIX DU CANADA 2025R

====================================================================================================
seed_page_4.txt
Length: 1920
| Bahrain | 02 Mar | Max VerstappenVER | Red Bull Racing Honda RBPT | 57 | 1:31:44.742 | | Saudi Arabia | 09 Mar | Max VerstappenVER | Red Bull Racing Honda RBPT | 50 | 1:20:43.273 | | Australia | 24 Mar | Carlos SainzSAI | Ferrari | 58 | 1:20:26.843 | | Japan | 07 Apr | Max VerstappenVER | Red Bull Racing Honda RBPT | 53 | 1:54:23.566 | | China | 21 Apr | Max VerstappenVER | Red Bull Racing Honda RBPT | 56 | 1:40:52.554 | | Miami | 05 May | Lando NorrisNOR | McLaren Mercedes | 57 | 1:30:49.876 | | Emilia-Romagna | 19 May | Max VerstappenVER | Red Bull Racing Honda RBPT | 63 | 1:25:25.252 | | Monaco | 26 May | Charles LeclercLEC | Ferrari | 78 | 2:23:15.554 | | Canada | 09 Jun | Max VerstappenVER | Red Bull Racing Honda RBPT | 70 | 1:45:47.927 | | Spain | 23 Jun | Max VerstappenVER | Red Bull Racing Honda RBPT | 66 | 1:28:20.227 | | Austria | 30 Jun | George RussellRUS | Mercedes | 71 | 1:24:22.798 | | Great Britain | 07 Jul | Lewis HamiltonHAM | Mercedes | 52 | 1:22:27.059 | | Hungary | 21 Jul | Oscar PiastriPIA | McLaren Mercedes | 70 | 1:38:01.989 | | Belgium | 28 Jul | Lewis HamiltonHAM | Mercedes | 44 | 1:19:57.566 | | Netherlands | 25 Aug | Lando NorrisNOR | McLaren Mercedes

====================================================================================================
seed_page_5.txt
Length: 140
Authentics Store Tickets Hospitality Experiences Previous Next Upcoming Inside the 2026 F1 titles shoot Team Bosses Unfiltered: Team Culture

====================================================================================================
seed_page_6.txt
Length: 362
2024 Teams' Standings | Pos. | Team | Pts. | |---|---|---| | 1 | McLaren Mercedes | 666 | | 2 | Ferrari | 652 | | 3 | Red Bull Racing Honda RBPT | 589 | | 4 | Mercedes | 468 | | 5 | Aston Martin Aramco Mercedes | 94 | | 6 | Alpine Renault | 65 | | 7 | Haas Ferrari | 58 | | 8 | RB Honda RBPT | 46 | | 9 | Williams Mercedes | 17 | | 10 | Kick Sauber Ferrari | 4 |

====================================================================================================
seed_page_7.txt
Length: 989
Formula One — or F1 for short — is the absolute top tier of open-wheel racing. Governed by the FIA (the Fédération Internationale de l’Automobile if you want the extended version), where technology, elite drivers, and teams fight for the Drivers’ and Constructors’ titles at over 200 mph. The “formula” part? That’s a fancy way of saying every team and driver must follow a strict set of rules — from car design to race weekend protocols. The heart of the F1 season is the World Championship, which is a series of races called Grands Prix held at purpose-built circuits and iconic street tracks worldwide. Drivers earn points based on how they finish in each race, and whoever racks up the most by season’s end is crowned World Champion. While a driver can technically clinch the title before the season wraps (once no one else can catch them in the points), the trophy itself isn’t handed over until the FIA’s annual Prize Giving Ceremony — a glamorous event that moves from city to city.

====================================================================================================
seed_page_8.txt
Length: 6752
Since the start of the Formula One World Championship in 1950, 78 different circuits have hosted at least one Grand Prix. These tracks range from permanent racing facilities to temporary street circuits built on public roads. | Circuit | Country | First Grand Prix | Circuit Length | Status | |---|---|---|---|---| | Australia | 1985 | 3.780 km | Historic | | | Morocco | 1958 | 7.603 km | Historic | | | United Kingdom | 1955 | 4.828 km | Historic | | | Australia | 1996 | 5.278km | Current | | | Portugal | 2020 | 4.653 km (2.891 mi) | Current | | | Sweden | 1973 | 4.018 km (1975–1977 F1 layout) | Historic | | | Portugal | 1984 | 4.360 km | Historic | | | Mexico | 1963 | 4.304km | Current | | | Brazil | 1978 | 5.031 km | Historic | | | Italy | 2020 | 5.245 km | Historic | | | Italy | 1980 | 4.909km | Current | | | Brazil | 1973 | 4.309km | Current | | | Italy | 1950 | 5.793km | Current | | | Argentina | 1953 | 4.259 km (2.646 miles) | Historic | | | Germany | 1959 | 8.300 km | Historic | | | Bahrain | 2004 | 5.412km | Current | | | Azerbaijan | 2016 | 6.003km | Current | | | United Kingdom | 1964 | 4.207 km | Historic | | | India | 2011 | 5.125 km | Historic | | | France | 1967 | 4.422

====================================================================================================
seed_page_9.txt
Length: 1151
Formula One also includes the Constructor standings in addition to the individual Driver standings. These standings are determined similarly to the driver standings, with points assigned based on the team drivers’ finishing positions. The team with the highest total points at the end of the season is declared the Constructors’ Champion. The F1 standings of the Formula One World Championship allow fans to follow each driver’s progress throughout the season and ultimately determine the championship winner. McLaren sealed the 2025 Constructors’ Championship with six races still to go, wrapping it up at the 2025 Singapore Grand Prix after a strong result from Lando Norris and Oscar Piastri. The win guaranteed their dominance in the current era, coming off the back of their 2024 triumph, which had already ended a 26-year drought since their previous constructors’ title in 1998. This 2025 success made it back-to-back Constructors’ Championships for McLaren, a historic return to when the team boasted multiple titles through the 1980s and early 1990s. It was the first time since 1991 that they had successfully defended a Constructors’ crown.

we will choose seed 7  and 9 mmay be 10 too because their note a list but more some text

In [13]:
from pathlib import Path

sample_path = Path("../data/processed/seed_page_7.txt")

with sample_path.open("r", encoding="utf-8") as file:
    text = file.read()

normalized_text = normalize_text(text)

doc = nlp(normalized_text)
entities = [(ent.text, ent.label_) for ent in doc.ents]
entities[:40]

[('F1', 'GPE'),
 ('FIA', 'ORG'),
 ('the Fédération Internationale de l’Automobile', 'ORG'),
 ('over 200 mph', 'QUANTITY'),
 ('weekend', 'DATE'),
 ('F1', 'GPE'),
 ('the World Championship', 'EVENT'),
 ('Grands Prix', 'ORG'),
 ('World Champion', 'ORG'),
 ('Prize Giving Ceremony', 'WORK_OF_ART')]

In [14]:
from pathlib import Path

sample_path = Path("../data/processed/seed_page_9.txt")

with sample_path.open("r", encoding="utf-8") as file:
    text = file.read()

normalized_text = normalize_text(text)

doc = nlp(normalized_text)
entities = [(ent.text, ent.label_) for ent in doc.ents]
entities[:50]

[('Formula One', 'ORG'),
 ('Constructor', 'LOC'),
 ('Driver', 'ORG'),
 ('the end of the season', 'DATE'),
 ('the Constructors’ Champion', 'ORG'),
 ('F1', 'GPE'),
 ('the season', 'DATE'),
 ('McLaren', 'PERSON'),
 ('2025', 'DATE'),
 ('Constructors’ Championship', 'WORK_OF_ART'),
 ('six', 'CARDINAL'),
 ('the 2025', 'EVENT'),
 ('Singapore Grand Prix', 'EVENT'),
 ('Lando Norris', 'ORG'),
 ('Oscar Piastri', 'PERSON'),
 ('2024', 'DATE'),
 ('26-year', 'DATE'),
 ('1998', 'DATE'),
 ('2025', 'DATE'),
 ('Constructors’ Championships', 'ORG'),
 ('McLaren', 'PERSON'),
 ('the 1980s', 'DATE'),
 ('early 1990s', 'DATE'),
 ('first', 'ORDINAL'),
 ('1991', 'DATE'),
 ('Constructors', 'ORG')]

In [15]:
from src.ie.ner_utils import load_ner_model, extract_entities

nlp = load_ner_model()

entities = extract_entities(normalized_text, nlp)
entities[:15]

[{'text': 'Formula One', 'label': 'ORG', 'start': 0, 'end': 11},
 {'text': 'Constructor', 'label': 'LOC', 'start': 30, 'end': 41},
 {'text': 'Driver', 'label': 'ORG', 'start': 82, 'end': 88},
 {'text': 'the end of the season', 'label': 'DATE', 'start': 277, 'end': 298},
 {'text': 'the Constructors’ Champion',
  'label': 'ORG',
  'start': 311,
  'end': 337},
 {'text': 'F1', 'label': 'GPE', 'start': 343, 'end': 345},
 {'text': 'the season', 'label': 'DATE', 'start': 449, 'end': 459},
 {'text': 'McLaren', 'label': 'PERSON', 'start': 510, 'end': 517},
 {'text': '2025', 'label': 'DATE', 'start': 529, 'end': 533},
 {'text': 'Constructors’ Championship',
  'label': 'WORK_OF_ART',
  'start': 534,
  'end': 560},
 {'text': 'six', 'label': 'CARDINAL', 'start': 566, 'end': 569},
 {'text': 'the 2025', 'label': 'EVENT', 'start': 607, 'end': 615},
 {'text': 'Singapore Grand Prix', 'label': 'EVENT', 'start': 616, 'end': 636},
 {'text': 'Lando Norris', 'label': 'ORG', 'start': 664, 'end': 676},
 {'text': 'Oscar Piastri', 'label': 'PERSON', 'start': 681, 'end': 694}]

In [16]:
import pandas as pd

entities_df = pd.DataFrame(entities)
entities_df.head(20)

                           text        label  start  end
0                   Formula One          ORG      0   11
1                   Constructor          LOC     30   41
2                        Driver          ORG     82   88
3         the end of the season         DATE    277  298
4    the Constructors’ Champion          ORG    311  337
5                            F1          GPE    343  345
6                    the season         DATE    449  459
7                       McLaren       PERSON    510  517
8                          2025         DATE    529  533
9    Constructors’ Championship  WORK_OF_ART    534  560
10                          six     CARDINAL    566  569
11                     the 2025        EVENT    607  615
12         Singapore Grand Prix        EVENT    616  636
13                 Lando Norris          ORG    664  676
14                Oscar Piastri       PERSON    681  694
15                         2024         DATE    780  784
16                      26-year         DATE    820  827
17                         1998         DATE    880  884
18                         2025         DATE    891  895
19  Constructors’ Championships          ORG    925  952

In [17]:
from pathlib import Path
import pandas as pd

from src.ie.preprocessing import normalize_text
from src.ie.ner_utils import load_ner_model, extract_entities

nlp = load_ner_model()

selected_files = [
    "seed_page_7.txt",
    "seed_page_9.txt",
    "seed_page_10.txt",
]

all_entities = []

for file_name in selected_files:
    file_path = Path("../data/processed") / file_name

    with file_path.open("r", encoding="utf-8") as file:
        text = file.read()

    normalized_text = normalize_text(text)
    entities = extract_entities(normalized_text, nlp)

    for entity in entities:
        entity["source_file"] = file_name

    all_entities.extend(entities)

entities_df = pd.DataFrame(all_entities)
entities_df.head(30)

,text,label,start,end,source_file
0,F1,GPE,17,19,seed_page_7.txt
1,FIA,ORG,95,98,seed_page_7.txt
2,the Fédération Internationale de l’Automobile,ORG,100,145,seed_page_7.txt
3,over 200 mph,QUANTITY,275,287,seed_page_7.txt
4,weekend,DATE,420,427,seed_page_7.txt
5,F1,GPE,456,458,seed_page_7.txt
6,the World Championship,EVENT,469,491,seed_page_7.txt
7,Grands Prix,ORG,527,538,seed_page_7.txt
8,World Champion,ORG,722,736,seed_page_7.txt
9,Prize Giving Ceremony,WORK_OF_ART,918,939,seed_page_7.txt
10,Formula One,ORG,0,11,seed_page_9.txt
11,Constructor,LOC,30,41,seed_page_9.txt
12,Driver,ORG,82,88,seed_page_9.txt
13,the end of the season,DATE,277,298,seed_page_9.txt
14,the Constructors’ Champion,ORG,311,337,seed_page_9.txt
15,F1,GPE,343,345,seed_page_9.txt
16,the season,DATE,449,459,seed_page_9.txt
17,McLaren,PERSON,510,517,seed_page_9.txt
18,2025,DATE,529,533,seed_page_9.txt
19,Constructors’ Championship,WORK_OF_ART,534,560,seed_page_9.txt
20,six,CARDINAL,566,569,seed_page_9.txt
21,the 2025,EVENT,607,615,seed_page_9.txt
22,Singapore Grand Prix,EVENT,616,636,seed_page_9.txt
23,Lando Norris,ORG,664,676,seed_page_9.txt
24,Oscar Piastri,PERSON,681,694,seed_page_9.txt
25,2024,DATE,780,784,seed_page_9.txt
26,26-year,DATE,820,827,seed_page_9.txt
27,1998,DATE,880,884,seed_page_9.txt
28,2025,DATE,891,895,seed_page_9.txt
29,Constructors’ Championships,ORG,925,952,seed_page_9.txt

In [18]:
entities_df["label"].value_counts()

label
DATE           58
PERSON         44
CARDINAL       33
ORG            19
GPE            10
ORDINAL         6
WORK_OF_ART     5
EVENT           4
QUANTITY        3
NORP            2
LOC             1
PRODUCT         1
LAW             1
Name: count, dtype: int64

In [19]:
entities_df.groupby("source_file")["label"].value_counts()

source_file       label
seed_page_10.txt  DATE           47
                  PERSON         41
                  CARDINAL       32
                  ORG             9
                  GPE             7
                  ORDINAL         5
                  WORK_OF_ART     3
                  QUANTITY        2
                  NORP            2
                  PRODUCT         1
                  EVENT           1
                  LAW             1
seed_page_7.txt   ORG             4
                  GPE             2
                  WORK_OF_ART     1
                  EVENT           1
                  DATE            1
                  QUANTITY        1
seed_page_9.txt   DATE           10
                  ORG             6
                  PERSON          3
                  EVENT           2
                  WORK_OF_ART     1
                  ORDINAL         1
                  GPE             1
                  LOC             1
                  CARDINAL        1
Name: count, dtype: int64

In [20]:
useful_labels = ["PERSON", "ORG", "EVENT", "DATE", "GPE"]

filtered_entities_df = entities_df[entities_df["label"].isin(useful_labels)].copy()
filtered_entities_df.head(30)

,text,label,start,end,source_file
0,F1,GPE,17,19,seed_page_7.txt
1,FIA,ORG,95,98,seed_page_7.txt
2,the Fédération Internationale de l’Automobile,ORG,100,145,seed_page_7.txt
4,weekend,DATE,420,427,seed_page_7.txt
5,F1,GPE,456,458,seed_page_7.txt
6,the World Championship,EVENT,469,491,seed_page_7.txt
7,Grands Prix,ORG,527,538,seed_page_7.txt
8,World Champion,ORG,722,736,seed_page_7.txt
10,Formula One,ORG,0,11,seed_page_9.txt
12,Driver,ORG,82,88,seed_page_9.txt
13,the end of the season,DATE,277,298,seed_page_9.txt
14,the Constructors’ Champion,ORG,311,337,seed_page_9.txt
15,F1,GPE,343,345,seed_page_9.txt
16,the season,DATE,449,459,seed_page_9.txt
17,McLaren,PERSON,510,517,seed_page_9.txt
18,2025,DATE,529,533,seed_page_9.txt
21,the 2025,EVENT,607,615,seed_page_9.txt
22,Singapore Grand Prix,EVENT,616,636,seed_page_9.txt
23,Lando Norris,ORG,664,676,seed_page_9.txt
24,Oscar Piastri,PERSON,681,694,seed_page_9.txt
25,2024,DATE,780,784,seed_page_9.txt
26,26-year,DATE,820,827,seed_page_9.txt
27,1998,DATE,880,884,seed_page_9.txt
28,2025,DATE,891,895,seed_page_9.txt
29,Constructors’ Championships,ORG,925,952,seed_page_9.txt
30,McLaren,PERSON,957,964,seed_page_9.txt
31,the 1980s,DATE,1033,1042,seed_page_9.txt
32,early 1990s,DATE,1047,1058,seed_page_9.txt
34,1991,DATE,1088,1092,seed_page_9.txt
35,Constructors,ORG,1131,1143,seed_page_9.txt

In [21]:
filtered_entities_df.groupby("source_file")["label"].value_counts()

source_file       label
seed_page_10.txt  DATE      47
                  PERSON    41
                  ORG        9
                  GPE        7
                  EVENT      1
seed_page_7.txt   ORG        4
                  GPE        2
                  DATE       1
                  EVENT      1
seed_page_9.txt   DATE      10
                  ORG        6
                  PERSON     3
                  EVENT      2
                  GPE        1
Name: count, dtype: int64

In [22]:
from src.ie.entity_mapping import map_entity_to_f1_type

filtered_entities_df["f1_type"] = filtered_entities_df.apply(
    lambda row: map_entity_to_f1_type(row["text"], row["label"]),
    axis=1,
)

filtered_entities_df[["text", "label", "f1_type", "source_file"]].head(30)

,text,label,f1_type,source_file
0,F1,GPE,CountryOrPlace,seed_page_7.txt
1,FIA,ORG,TeamOrOrganization,seed_page_7.txt
2,the Fédération Internationale de l’Automobile,ORG,TeamOrOrganization,seed_page_7.txt
4,weekend,DATE,NaN,seed_page_7.txt
5,F1,GPE,CountryOrPlace,seed_page_7.txt
6,the World Championship,EVENT,NaN,seed_page_7.txt
7,Grands Prix,ORG,TeamOrOrganization,seed_page_7.txt
8,World Champion,ORG,TeamOrOrganization,seed_page_7.txt
10,Formula One,ORG,TeamOrOrganization,seed_page_9.txt
12,Driver,ORG,TeamOrOrganization,seed_page_9.txt
13,the end of the season,DATE,NaN,seed_page_9.txt
14,the Constructors’ Champion,ORG,TeamOrOrganization,seed_page_9.txt
15,F1,GPE,CountryOrPlace,seed_page_9.txt
16,the season,DATE,NaN,seed_page_9.txt
17,McLaren,PERSON,DriverOrPerson,seed_page_9.txt
18,2025,DATE,Season,seed_page_9.txt
21,the 2025,EVENT,NaN,seed_page_9.txt
22,Singapore Grand Prix,EVENT,GrandPrix,seed_page_9.txt
23,Lando Norris,ORG,TeamOrOrganization,seed_page_9.txt
24,Oscar Piastri,PERSON,DriverOrPerson,seed_page_9.txt
25,2024,DATE,Season,seed_page_9.txt
26,26-year,DATE,NaN,seed_page_9.txt
27,1998,DATE,Season,seed_page_9.txt
28,2025,DATE,Season,seed_page_9.txt
29,Constructors’ Championships,ORG,TeamOrOrganization,seed_page_9.txt
30,McLaren,PERSON,DriverOrPerson,seed_page_9.txt
31,the 1980s,DATE,NaN,seed_page_9.txt
32,early 1990s,DATE,NaN,seed_page_9.txt
34,1991,DATE,Season,seed_page_9.txt
35,Constructors,ORG,TeamOrOrganization,seed_page_9.txt

In [23]:
filtered_entities_df["f1_type"].value_counts(dropna=False)

f1_type
DriverOrPerson        44
Season                40
NaN                   21
TeamOrOrganization    17
CountryOrPlace        10
GrandPrix              3
Name: count, dtype: int64

In [24]:
candidate_entities_df = (
    filtered_entities_df[["text", "f1_type", "source_file"]]
    .dropna(subset=["f1_type"])
    .drop_duplicates()
    .sort_values(["f1_type", "text"])
)

candidate_entities_df.head(50)

                               text         f1_type       source_file
57                         Adelaide  CountryOrPlace  seed_page_10.txt
0                                F1  CountryOrPlace   seed_page_7.txt
15                               F1  CountryOrPlace   seed_page_9.txt
47                               F1  CountryOrPlace  seed_page_10.txt
58                        Melbourne  CountryOrPlace  seed_page_10.txt
158                  Alberto Ascari  DriverOrPerson  seed_page_10.txt
92                     Ayrton Senna  DriverOrPerson  seed_page_10.txt
103                          Driver  DriverOrPerson  seed_page_10.txt
93                  Fernando Alonso  DriverOrPerson  seed_page_10.txt
142                         Formula  DriverOrPerson  seed_page_10.txt
84                    Formula One’s  DriverOrPerson  seed_page_10.txt
183                    Jack Brabham  DriverOrPerson  seed_page_10.txt
184                       Jim Clark  DriverOrPerson  seed_page_10.txt
159              Juan Manuel Fangio  DriverOrPerson  seed_page_10.txt
161                    Lando Norris  DriverOrPerson  seed_page_10.txt
83                   Lewis Hamilton  DriverOrPerson  seed_page_10.txt
88                   Max Verstappen  DriverOrPerson  seed_page_10.txt
17                          McLaren  DriverOrPerson   seed_page_9.txt
86               Michael Schumacher  DriverOrPerson  seed_page_10.txt
177                    Nico Rosberg  DriverOrPerson  seed_page_10.txt
94                    Nigel Mansell  DriverOrPerson  seed_page_10.txt
24                    Oscar Piastri  DriverOrPerson   seed_page_9.txt
162                   Oscar Piastri  DriverOrPerson  seed_page_10.txt
99                       Schumacher  DriverOrPerson  seed_page_10.txt
89                 Sebastian Vettel  DriverOrPerson  seed_page_10.txt
64                        Spielberg  DriverOrPerson  seed_page_10.txt
96                     Verstappen’s  DriverOrPerson  seed_page_10.txt
102                            Wins  DriverOrPerson  seed_page_10.txt
44             Abu Dhabi Grand Prix       GrandPrix  seed_page_10.txt
71   Barcelona-Catalunya Grand Prix       GrandPrix  seed_page_10.txt
22             Singapore Grand Prix       GrandPrix   seed_page_9.txt
43                             1950          Season  seed_page_10.txt
173                            1952          Season  seed_page_10.txt
48                             1953          Season  seed_page_10.txt
60                             1964          Season  seed_page_10.txt
80                             1973          Season  seed_page_10.txt
54                             1985          Season  seed_page_10.txt
34                             1991          Season   seed_page_9.txt
75                             1991          Season  seed_page_10.txt
27                             1998          Season   seed_page_9.txt
49                             1998          Season  seed_page_10.txt
123                            2002          Season  seed_page_10.txt
69                             2004          Season  seed_page_10.txt
45                             2009          Season  seed_page_10.txt
127                            2011          Season  seed_page_10.txt
119                            2013          Season  seed_page_10.txt
70                             2014          Season  seed_page_10.txt
178                            2015          Season  seed_page_10.txt
179                            2016          Season  seed_page_10.txt
66                             2017          Season  seed_page_10.txt

In [25]:
candidate_entities_df.groupby("f1_type").size()

f1_type
CountryOrPlace         5
DriverOrPerson        23
GrandPrix              3
Season                27
TeamOrOrganization    17
dtype: int64

In [26]:
for f1_type in candidate_entities_df["f1_type"].dropna().unique():
    print("=" * 80)
    print(f1_type)
    print(candidate_entities_df[candidate_entities_df["f1_type"] == f1_type]["text"].tolist()[:20])
    print()

================================================================================
CountryOrPlace
['Adelaide', 'F1', 'F1', 'F1', 'Melbourne']

================================================================================
DriverOrPerson
['Alberto Ascari', 'Ayrton Senna', 'Driver', 'Fernando Alonso', 'Formula', 'Formula One’s', 'Jack Brabham', 'Jim Clark', 'Juan Manuel Fangio', 'Lando Norris', 'Lewis Hamilton', 'Max Verstappen', 'McLaren', 'Michael Schumacher', 'Nico Rosberg', 'Nigel Mansell', 'Oscar Piastri', 'Oscar Piastri', 'Schumacher', 'Sebastian Vettel']

================================================================================
GrandPrix
['Abu Dhabi Grand Prix', 'Barcelona-Catalunya Grand Prix', 'Singapore Grand Prix']

================================================================================
Season
['1950', '1952', '1953', '1964', '1973', '1985', '1991', '1991', '1998', '1998', '2002', '2004', '2009', '2011', '2013', '2014', '2015', '2016', '2017', '2018']

================================================================================
TeamOrOrganization
['Alain Prost', 'Circuit de Barcelona-Catalunya', 'Constructors', 'Constructors’ Championships', 'Driver', 'FIA', 'Ferrari', 'Formula One', 'Formula One', 'Grands Prix', 'Lando Norris', 'Races', 'Vettel', 'World Champion', 'Zeltweg, Osterreichring', 'the Constructors’ Champion', 'the Fédération Internationale de l’Automobile']

In [27]:
from src.ie.entity_mapping import map_entity_to_f1_type

filtered_entities_df["f1_type"] = filtered_entities_df.apply(
    lambda row: map_entity_to_f1_type(row["text"], row["label"]),
    axis=1,
)

candidate_entities_df = (
    filtered_entities_df[["text", "f1_type", "source_file"]]
    .dropna(subset=["f1_type"])
    .drop_duplicates()
    .sort_values(["f1_type", "text"])
)

for f1_type in candidate_entities_df["f1_type"].dropna().unique():
    print("=" * 80)
    print(f1_type)
    print(candidate_entities_df[candidate_entities_df["f1_type"] == f1_type]["text"].tolist()[:20])
    print()

================================================================================
CountryOrPlace
['Adelaide', 'Melbourne']

================================================================================
Driver
['Alberto Ascari', 'Ayrton Senna', 'Fernando Alonso', 'Jack Brabham', 'Jim Clark', 'Juan Manuel Fangio', 'Lando Norris', 'Lewis Hamilton', 'Max Verstappen', 'Michael Schumacher', 'Nico Rosberg', 'Nigel Mansell', 'Oscar Piastri', 'Oscar Piastri', 'Schumacher', 'Sebastian Vettel', 'Spielberg', 'Verstappen’s', 'Wins']

================================================================================
GrandPrix
['Abu Dhabi Grand Prix', 'Barcelona-Catalunya Grand Prix', 'Singapore Grand Prix']

================================================================================
Season
['1950', '1952', '1953', '1964', '1973', '1985', '1991', '1991', '1998', '1998', '2002', '2004', '2009', '2011', '2013', '2014', '2015', '2016', '2017', '2018']

================================================================================
Team
['Ferrari', 'McLaren']

================================================================================
TeamOrOrganization
['Alain Prost', 'Circuit de Barcelona-Catalunya', 'Driver', 'FIA', 'Formula One', 'Formula One', 'Lando Norris', 'Vettel', 'Zeltweg, Osterreichring', 'the Fédération Internationale de l’Automobile']

In [29]:
from src.ie.entity_filters import is_valid_f1_entity

clean_candidate_entities_df = candidate_entities_df[
    candidate_entities_df.apply(
        lambda row: is_valid_f1_entity(row["text"], row["f1_type"]),
        axis=1,
    )
].copy()

for f1_type in clean_candidate_entities_df["f1_type"].dropna().unique():
    print("=" * 80)
    print(f1_type)
    print(clean_candidate_entities_df[clean_candidate_entities_df["f1_type"] == f1_type]["text"].tolist()[:20])
    print()

================================================================================
CountryOrPlace
['Adelaide', 'Melbourne']

================================================================================
Driver
['Alberto Ascari', 'Ayrton Senna', 'Fernando Alonso', 'Jack Brabham', 'Jim Clark', 'Juan Manuel Fangio', 'Lando Norris', 'Lewis Hamilton', 'Max Verstappen', 'Michael Schumacher', 'Nico Rosberg', 'Nigel Mansell', 'Oscar Piastri', 'Oscar Piastri', 'Schumacher', 'Sebastian Vettel']

================================================================================
GrandPrix
['Abu Dhabi Grand Prix', 'Barcelona-Catalunya Grand Prix', 'Singapore Grand Prix']

================================================================================
Season
['1950', '1952', '1953', '1964', '1973', '1985', '1991', '1991', '1998', '1998', '2002', '2004', '2009', '2011', '2013', '2014', '2015', '2016', '2017', '2018']

================================================================================
Team
['Ferrari', 'McLaren']

================================================================================
TeamOrOrganization
['FIA', 'Zeltweg, Osterreichring', 'the Fédération Internationale de l’Automobile']

In [30]:
from src.ie.entity_normalization import normalize_entity_name

clean_candidate_entities_df["normalized_text"] = clean_candidate_entities_df["text"].apply(normalize_entity_name)

entity_catalog_df = (
    clean_candidate_entities_df[["normalized_text", "f1_type"]]
    .drop_duplicates()
    .sort_values(["f1_type", "normalized_text"])
)

entity_catalog_df.head(50)

                    normalized_text             f1_type
57                         Adelaide      CountryOrPlace
58                        Melbourne      CountryOrPlace
158                  Alberto Ascari              Driver
92                     Ayrton Senna              Driver
93                  Fernando Alonso              Driver
183                    Jack Brabham              Driver
184                       Jim Clark              Driver
159              Juan Manuel Fangio              Driver
161                    Lando Norris              Driver
83                   Lewis Hamilton              Driver
88                   Max Verstappen              Driver
86               Michael Schumacher              Driver
177                    Nico Rosberg              Driver
94                    Nigel Mansell              Driver
24                    Oscar Piastri              Driver
99                       Schumacher              Driver
89                 Sebastian Vettel              Driver
44             Abu Dhabi Grand Prix           GrandPrix
71   Barcelona-Catalunya Grand Prix           GrandPrix
22             Singapore Grand Prix           GrandPrix
43                             1950              Season
173                            1952              Season
48                             1953              Season
60                             1964              Season
80                             1973              Season
54                             1985              Season
34                             1991              Season
27                             1998              Season
123                            2002              Season
69                             2004              Season
45                             2009              Season
127                            2011              Season
119                            2013              Season
70                             2014              Season
178                            2015              Season
179                            2016              Season
66                             2017              Season
134                            2018              Season
81                             2019              Season
38                             2020              Season
110                            2022              Season
98                             2023              Season
25                             2024              Season
18                             2025              Season
72                             2026              Season
100                         Ferrari                Team
17                          McLaren                Team
1                               FIA  TeamOrOrganization
63          Zeltweg, Osterreichring  TeamOrOrganization

In [31]:
entity_catalog_df["f1_type"].value_counts()

f1_type
Season                25
Driver                15
GrandPrix              3
CountryOrPlace         2
Team                   2
TeamOrOrganization     2
Name: count, dtype: int64

In [32]:
for f1_type in entity_catalog_df["f1_type"].dropna().unique():
    print("=" * 80)
    print(f1_type)
    print(entity_catalog_df[entity_catalog_df["f1_type"] == f1_type]["normalized_text"].tolist()[:20])
    print()

================================================================================
CountryOrPlace
['Adelaide', 'Melbourne']

================================================================================
Driver
['Alberto Ascari', 'Ayrton Senna', 'Fernando Alonso', 'Jack Brabham', 'Jim Clark', 'Juan Manuel Fangio', 'Lando Norris', 'Lewis Hamilton', 'Max Verstappen', 'Michael Schumacher', 'Nico Rosberg', 'Nigel Mansell', 'Oscar Piastri', 'Schumacher', 'Sebastian Vettel']

================================================================================
GrandPrix
['Abu Dhabi Grand Prix', 'Barcelona-Catalunya Grand Prix', 'Singapore Grand Prix']

================================================================================
Season
['1950', '1952', '1953', '1964', '1973', '1985', '1991', '1998', '2002', '2004', '2009', '2011', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020']

================================================================================
Team
['Ferrari', 'McLaren']

================================================================================
TeamOrOrganization
['FIA', 'Zeltweg, Osterreichring']

In [33]:
from src.ie.io_utils import save_dataframe

save_dataframe(entity_catalog_df, "../data/processed/entity_catalog.csv")
print("Entity catalog saved.")

Entity catalog saved.

In [34]:
import pandas as pd

saved_entity_catalog_df = pd.read_csv("../data/processed/entity_catalog.csv")
saved_entity_catalog_df.head(20)

                   normalized_text         f1_type
0                         Adelaide  CountryOrPlace
1                        Melbourne  CountryOrPlace
2                   Alberto Ascari          Driver
3                     Ayrton Senna          Driver
4                  Fernando Alonso          Driver
5                     Jack Brabham          Driver
6                        Jim Clark          Driver
7               Juan Manuel Fangio          Driver
8                     Lando Norris          Driver
9                   Lewis Hamilton          Driver
10                  Max Verstappen          Driver
11              Michael Schumacher          Driver
12                    Nico Rosberg          Driver
13                   Nigel Mansell          Driver
14                   Oscar Piastri          Driver
15                      Schumacher          Driver
16                Sebastian Vettel          Driver
17            Abu Dhabi Grand Prix       GrandPrix
18  Barcelona-Catalunya Grand Prix       GrandPrix
19            Singapore Grand Prix       GrandPrix

In [35]:
from pathlib import Path
import pandas as pd

from src.ie.preprocessing import normalize_text
from src.ie.ner_utils import load_ner_model
from src.ie.relation_candidates import extract_relation_candidates

nlp = load_ner_model()

sample_path = Path("../data/processed/seed_page_9.txt")
with sample_path.open("r", encoding="utf-8") as file:
    text = file.read()

normalized_text = normalize_text(text)

relation_candidates = extract_relation_candidates(normalized_text, nlp)
relation_candidates_df = pd.DataFrame(relation_candidates)

relation_candidates_df.head(20)

,sentence,entity_1,entity_1_type,entity_2,entity_2_type
0,McLaren sealed the 2025 Constructors’ Champion...,McLaren,Team,2025,Season
1,McLaren sealed the 2025 Constructors’ Champion...,McLaren,Team,Singapore Grand Prix,GrandPrix
2,McLaren sealed the 2025 Constructors’ Champion...,McLaren,Team,Oscar Piastri,Driver
3,McLaren sealed the 2025 Constructors’ Champion...,2025,Season,Singapore Grand Prix,GrandPrix
4,McLaren sealed the 2025 Constructors’ Champion...,2025,Season,Oscar Piastri,Driver
5,McLaren sealed the 2025 Constructors’ Champion...,Singapore Grand Prix,GrandPrix,Oscar Piastri,Driver
6,The win guaranteed their dominance in the curr...,2024,Season,1998,Season
7,This 2025 success made it back-to-back Constru...,2025,Season,McLaren,Team

In [36]:
relation_candidates_df[["entity_1_type", "entity_2_type"]].value_counts()

entity_1_type  entity_2_type
Team           Season           1
               GrandPrix        1
               Driver           1
Season         GrandPrix        1
               Driver           1
GrandPrix      Driver           1
Season         Season           1
               Team             1
Name: count, dtype: int64

In [40]:
from src.ie.relation_mapping import infer_f1_relation

relation_candidates_df["relation_type"] = relation_candidates_df.apply(
    lambda row: infer_f1_relation(
        row["sentence"],
        row["entity_1"],
        row["entity_1_type"],
        row["entity_2"],
        row["entity_2_type"],
    ),
    axis=1,
)

relation_candidates_df[
    ["entity_1", "entity_1_type", "entity_2", "entity_2_type", "relation_type"]
]

,entity_1,entity_1_type,entity_2,entity_2_type,relation_type
0,McLaren,Team,2025,Season,wonConstructorsChampionshipIn
1,McLaren,Team,Singapore Grand Prix,GrandPrix,NaN
2,McLaren,Team,Oscar Piastri,Driver,NaN
3,2025,Season,Singapore Grand Prix,GrandPrix,isPartOfSeason
4,2025,Season,Oscar Piastri,Driver,NaN
5,Singapore Grand Prix,GrandPrix,Oscar Piastri,Driver,NaN
6,2024,Season,1998,Season,NaN
7,2025,Season,McLaren,Team,wonConstructorsChampionshipIn

In [41]:
relation_candidates_df["relation_type"].value_counts(dropna=False)

relation_type
NaN                              5
wonConstructorsChampionshipIn    2
isPartOfSeason                   1
Name: count, dtype: int64

In [42]:
mapped_relations_df = relation_candidates_df.dropna(subset=["relation_type"]).copy()
mapped_relations_df[
    ["sentence", "entity_1", "entity_1_type", "entity_2", "entity_2_type", "relation_type"]
]

,sentence,entity_1,entity_1_type,entity_2,entity_2_type,relation_type
0,McLaren sealed the 2025 Constructors’ Champion...,McLaren,Team,2025,Season,wonConstructorsChampionshipIn
3,McLaren sealed the 2025 Constructors’ Champion...,2025,Season,Singapore Grand Prix,GrandPrix,isPartOfSeason
7,This 2025 success made it back-to-back Constru...,2025,Season,McLaren,Team,wonConstructorsChampionshipIn

In [43]:
unique_relations_df = (
    mapped_relations_df[
        ["entity_1", "entity_1_type", "entity_2", "entity_2_type", "relation_type"]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

unique_relations_df

,entity_1,entity_1_type,entity_2,entity_2_type,relation_type
0,McLaren,Team,2025,Season,wonConstructorsChampionshipIn
1,2025,Season,Singapore Grand Prix,GrandPrix,isPartOfSeason
2,2025,Season,McLaren,Team,wonConstructorsChampionshipIn

In [44]:
unique_relations_df["relation_type"].value_counts()

relation_type
wonConstructorsChampionshipIn    2
isPartOfSeason                   1
Name: count, dtype: int64

In [48]:
from src.ie.relation_normalization import normalize_relation_direction

normalized_relations = unique_relations_df.apply(
    lambda row: normalize_relation_direction(
        row["entity_1"],
        row["entity_1_type"],
        row["entity_2"],
        row["entity_2_type"],
        row["relation_type"],
    ),
    axis=1,
)

normalized_relations = [r for r in normalized_relations if r is not None]
normalized_relations_df = pd.DataFrame(normalized_relations).drop_duplicates().reset_index(drop=True)

normalized_relations_df

,subject,subject_type,predicate,object,object_type
0,McLaren,Team,wonConstructorsChampionshipIn,2025,Season
1,Singapore Grand Prix,GrandPrix,isPartOfSeason,2025,Season

In [49]:
normalized_relations_df["predicate"].value_counts()

predicate
wonConstructorsChampionshipIn    1
isPartOfSeason                   1
Name: count, dtype: int64

In [50]:
from src.ie.io_utils import save_dataframe

save_dataframe(normalized_relations_df, "../data/processed/relation_catalog.csv")
print("Relation catalog saved.")

Relation catalog saved.

In [51]:
import pandas as pd

saved_relation_catalog_df = pd.read_csv("../data/processed/relation_catalog.csv")
saved_relation_catalog_df

,subject,subject_type,predicate,object,object_type
0,McLaren,Team,wonConstructorsChampionshipIn,2025,Season
1,Singapore Grand Prix,GrandPrix,isPartOfSeason,2025,Season

In [52]:
from src.ie.pipeline import process_ie_folder

entity_catalog_df, relation_catalog_df = process_ie_folder("../data/processed")

entity_catalog_df.head(20)

   entity_text     entity_type       source_file
0    Abu Dhabi  CountryOrPlace   seed_page_4.txt
1     Adelaide  CountryOrPlace  seed_page_10.txt
2    Argentina  CountryOrPlace   seed_page_8.txt
3    Australia  CountryOrPlace   seed_page_4.txt
4    Australia  CountryOrPlace   seed_page_8.txt
5      Austria  CountryOrPlace   seed_page_4.txt
6      Austria  CountryOrPlace   seed_page_8.txt
7   Azerbaijan  CountryOrPlace   seed_page_4.txt
8   Azerbaijan  CountryOrPlace   seed_page_8.txt
9      Bahrain  CountryOrPlace   seed_page_4.txt
10     Bahrain  CountryOrPlace   seed_page_8.txt
11     Belgium  CountryOrPlace   seed_page_4.txt
12     Belgium  CountryOrPlace   seed_page_8.txt
13      Brazil  CountryOrPlace   seed_page_3.txt
14      Brazil  CountryOrPlace   seed_page_4.txt
15      Brazil  CountryOrPlace   seed_page_8.txt
16      Canada  CountryOrPlace   seed_page_4.txt
17      Canada  CountryOrPlace   seed_page_8.txt
18       China  CountryOrPlace   seed_page_4.txt
19       China  CountryOrPlace   seed_page_8.txt

In [53]:
relation_catalog_df.head(20)

,subject,subject_type,predicate,object,object_type,source_file
0,Abu Dhabi Grand Prix,GrandPrix,isPartOfSeason,2009,Season,seed_page_10.txt
1,Azerbaijan Grand Prix,GrandPrix,isPartOfSeason,2017,Season,seed_page_10.txt
2,Barcelona-Catalunya Grand Prix,GrandPrix,isPartOfSeason,1991,Season,seed_page_10.txt
3,Barcelona-Catalunya Grand Prix,GrandPrix,isPartOfSeason,2026,Season,seed_page_10.txt
4,Belgian Grand Prix,GrandPrix,isPartOfSeason,1950,Season,seed_page_10.txt
5,Brazilian Grand Prix,GrandPrix,isPartOfSeason,1973,Season,seed_page_10.txt
6,Brazilian Grand Prix,GrandPrix,isPartOfSeason,2019,Season,seed_page_10.txt
7,Grand Prix,GrandPrix,isPartOfSeason,1950,Season,seed_page_8.txt
8,Pescara Grand Prix,GrandPrix,isPartOfSeason,1957,Season,seed_page_8.txt
9,Singapore Grand Prix,GrandPrix,isPartOfSeason,2025,Season,seed_page_9.txt
10,The Italian Grand Prix,GrandPrix,isPartOfSeason,1950,Season,seed_page_8.txt
11,McLaren,Team,wonConstructorsChampionshipIn,2025,Season,seed_page_9.txt

In [54]:
entity_catalog_df["entity_type"].value_counts()

entity_type
Season                81
CountryOrPlace        72
Driver                62
TeamOrOrganization    23
GrandPrix             11
Team                   8
Name: count, dtype: int64

In [55]:
relation_catalog_df["predicate"].value_counts()

predicate
isPartOfSeason                   11
wonConstructorsChampionshipIn     1
Name: count, dtype: int64

In [56]:
from src.ie.io_utils import save_dataframe

save_dataframe(entity_catalog_df, "../data/processed/entity_catalog_batch.csv")
save_dataframe(relation_catalog_df, "../data/processed/relation_catalog_batch.csv")

print("Batch IE outputs saved.")

Batch IE outputs saved.

In [57]:
import pandas as pd

saved_entities = pd.read_csv("../data/processed/entity_catalog_batch.csv")
saved_relations = pd.read_csv("../data/processed/relation_catalog_batch.csv")

print(saved_entities.shape)
print(saved_relations.shape)

(257, 3)
(12, 6)